# Wrangler configuration for Cloudflare Pages deployment
name = "finanza-react-app"
compatibility_date = "2024-12-19"

# Build configuration
[build]
command = "npm run build"

# Directory to upload (where the built files are)
[build.upload]
dir = "dist"

# Environment-specific configurations
[env.production]
name = "finanza-react-app"

[env.staging]
name = "finanza-react-app-staging"

[env.development]
name = "finanza-react-app-dev"

# Pages-specific configuration
[[pages]]
name = "finanza-react-app"

# Deployment rules
[[pages.deployment_configs.production]]
environment = "production"

[[pages.deployment_configs.preview]]
environment = "preview"

# Headers configuration
[[pages.headers]]
for = "/*"
[pages.headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"

# Cache control for assets
[[pages.headers]]
for = "/assets/*"
[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[pages.headers]]
for = "/*.js"
[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[pages.headers]]
for = "/*.css"
[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Disable caching for index.html
[[pages.headers]]
for = "/index.html"
[pages.headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

# Redirect rules (if needed)
# [[pages.redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301

# Functions directory (if using Cloudflare Functions)
# [pages.functions]
# directory = "functions"
